# Generated by Django 5.1.2 on 2024-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('LIFE', 'Lifestyle'), ('TRVL', 'Travel'), ('EDU', 'Education'), ('FIN', 'Finance'), ('FOOD', 'Food')], max_length=10),
        ),
    ]
