# Generated by Django 5.1.2 on 2024-10-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Education', 'Education'), ('Finance', 'Finance'), ('Food', 'Food'), ('Story', 'Story'), ('Other', 'Other')], max_length=10),
        ),
    ]
